# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0b25aa84eb97a0a0c689abf5a6673aa"
name = "Donate-Me"
handle = "donate-me-1"
application_url = "https://dealers-variety-notifications-components.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_merchant_managed_fulfillment_orders,read_products,read_publications,write_assigned_fulfillment_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_publications,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://dealers-variety-notifications-components.trycloudflare.com/auth/callback",
  "https://dealers-variety-notifications-components.trycloudflare.com/auth/shopify/callback",
  "https://dealers-variety-notifications-components.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
